-- begin SALESGR_ORDER
alter table SALESGR_ORDER add constraint FK_SALESGR_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SALESGR_CUSTOMER(ID)^
create index IDX_SALESGR_ORDER_ON_CUSTOMER on SALESGR_ORDER (CUSTOMER_ID)^
-- end SALESGR_ORDER
